### ISSUE TITLE
Dev分支的后端代码存在数据库查询参数无法绑定的问题

### ISSUE THREAD

**Issue by sospink** [WeBankBlockchain/DDCMS-Service#2]
![f1c8c66ed5adf318a078be62f3447ea](https://github.com/WeBankBlockchain/DDCMS-Service/assets/84267606/fba39848-e268-48fd-87d8-58c49a180d37)
![c64d02f6d9cceb080cf67dbbaed57e0](https://github.com/WeBankBlockchain/DDCMS-Service/assets/84267606/a92762da-3ae5-4d8f-a26e-f3af530cef5e)

**Comment by CN-ZHANGYH** [comment]
问题已经解决：https://github.com/WeBankBlockchain/DDCMS-Service/pull/3

**Comment by CN-ZHANGYH** [comment]
https://github.com/WeBankBlockchain/DDCMS-Service/pull/3

**Comment by sospink** [comment]
该问题已经解决：https://github.com/WeBankBlockchain/DDCMS-Service/pull/3
- 修改了当前的AccountInfoMapper的代码
- 修改了当前的CompanyInfoMapper的代码
- 使用@Param注解重新绑定的参数
